# -*- coding: utf-8 -*-
"""Final3_Son.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aCEL40RUeimTe6npFPxrDchCZtrE2EYz
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from google.colab import drive

# 1. Google Drive bağla (Colab için)
drive.mount('/content/drive')

# 2. Dosya yolları (örnek)
file1 = "/content/drive/MyDrive/Kemal Hoca/Final3/DATABASE/IRIS.csv"
file2 = "/content/drive/MyDrive/Kemal Hoca/Final3/DATABASE/iris 2.csv"
file3 = "/content/drive/MyDrive/Kemal Hoca/Final3/DATABASE/Iris3.csv"

# 3. Dosyaları oku
df1 = pd.read_csv(file1)
df2 = pd.read_csv(file2)
df3 = pd.read_csv(file3)

# 4. Veri setlerini incele
print(df1.head())
print(df2.head())
print(df3.head())

print("df1 columns:", df1.columns.tolist())
print("df2 columns:", df2.columns.tolist())
print("df3 columns:", df3.columns.tolist())

# df3'te 'Id' sütununu kaldıralım
df3 = df3.drop(columns=['Id'])

# df3 sütun isimlerini df1 ve df2 ile aynı hale getirelim
df3 = df3.rename(columns={
    'SepalLengthCm': 'sepal_length',
    'SepalWidthCm': 'sepal_width',
    'PetalLengthCm': 'petal_length',
    'PetalWidthCm': 'petal_width',
    'Species': 'species'
})

# Kontrol için sütunları yazdır
print("df3 columns after rename:", df3.columns.tolist())

# 5. Ortak sütunları seç (örneğin klasik iris: 'sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species')
features = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
target = 'species'

# Eğer target farklı isimdeyse normalize etmek gerekebilir. Burada doğrudan species olduğunu varsayıyoruz.

# 6. Etiketleri sayısal hale dönüştür
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

def preprocess(df):
    df = df.dropna()  # boş varsa temizle
    X = df[features].values
    y = le.fit_transform(df[target].values)
    return X, y

X1, y1 = preprocess(df1)
X2, y2 = preprocess(df2)
X3, y3 = preprocess(df3)

# 7. Train-test split yap (aynı random_state ile stratify ederek)
def split_data(X, y):
    return train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

X1_train, X1_test, y1_train, y1_test = split_data(X1, y1)
X2_train, X2_test, y2_train, y2_test = split_data(X2, y2)
X3_train, X3_test, y3_train, y3_test = split_data(X3, y3)

# 8. Ölçekleme
scaler1 = StandardScaler().fit(X1_train)
scaler2 = StandardScaler().fit(X2_train)
scaler3 = StandardScaler().fit(X3_train)

X1_train_scaled = scaler1.transform(X1_train)
X1_test_scaled = scaler1.transform(X1_test)

X2_train_scaled = scaler2.transform(X2_train)
X2_test_scaled = scaler2.transform(X2_test)

X3_train_scaled = scaler3.transform(X3_train)
X3_test_scaled = scaler3.transform(X3_test)

# 9. Modelleri eğit
model1 = RandomForestClassifier(random_state=42)
model2 = GradientBoostingClassifier(random_state=42)
model3 = SVC(probability=True, random_state=42)

model1.fit(X1_train_scaled, y1_train)
model2.fit(X2_train_scaled, y2_train)
model3.fit(X3_train_scaled, y3_train)

# 10. Ensemble için ortak test seti olarak df1 test setini kullanacağız (X1_test_scaled ve y1_test)
# Diğer modeller için test verisini uygun scaler ile ölçekle
proba1 = model1.predict_proba(X1_test_scaled)
proba2 = model2.predict_proba(scaler2.transform(X1_test))
proba3 = model3.predict_proba(scaler3.transform(X1_test))

weights = [0.4, 0.35, 0.25]
ensemble_proba = weights[0]*proba1 + weights[1]*proba2 + weights[2]*proba3
ensemble_preds = np.argmax(ensemble_proba, axis=1)

# 11. Sonuçları göster
acc1 = accuracy_score(y1_test, model1.predict(X1_test_scaled))
acc2 = accuracy_score(y1_test, model2.predict(scaler2.transform(X1_test)))
acc3 = accuracy_score(y1_test, model3.predict(scaler3.transform(X1_test)))
acc_ensemble = accuracy_score(y1_test, ensemble_preds)

print(f"Model 1 (RF) Doğruluk: {acc1:.4f}")
print(f"Model 2 (GB) Doğruluk: {acc2:.4f}")
print(f"Model 3 (SVM) Doğruluk: {acc3:.4f}")
print(f"Ensemble Model Doğruluk: {acc_ensemble:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
import pandas as pd

# Tahminler
y_preds = {
    "Model 1 (RF)": model1.predict(X1_test_scaled),
    "Model 2 (GB)": model2.predict(scaler2.transform(X1_test)),
    "Model 3 (SVM)": model3.predict(scaler3.transform(X1_test)),
    "Ensemble": ensemble_preds
}

# Sınıf isimleri
class_names = le.classes_

# 1. Confusion Matrix'leri yan yana çiz
fig, axes = plt.subplots(1, 4, figsize=(20, 5))

for ax, (name, y_pred) in zip(axes, y_preds.items()):
    cm = confusion_matrix(y1_test, y_pred)
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False,
                xticklabels=class_names, yticklabels=class_names, ax=ax)
    ax.set_title(name)
    ax.set_xlabel('Tahmin')
    ax.set_ylabel('Gerçek')

plt.tight_layout()
plt.show()

# 2. Classification Report'ları tablo haline getir ve yazdır

def report_to_df(report_str):
    report_data = []
    lines = report_str.strip().split('\n')
    for line in lines[2:-3]:
        row = line.strip().split()
        if len(row) < 4:  # Boşlukları düzenle
            continue
        report_data.append({
            "Class": row[0],
            "Precision": float(row[1]),
            "Recall": float(row[2]),
            "F1-Score": float(row[3]),
            "Support": int(row[4])
        })
    return pd.DataFrame(report_data)

# Raporları dataframeler haline getir
dfs = {}
for name, y_pred in y_preds.items():
    report = classification_report(y1_test, y_pred, target_names=class_names)
    dfs[name] = report_to_df(report)

# 3. Tabloyu görselleştir
fig, axes = plt.subplots(2, 2, figsize=(18, 5))
axes = axes.flatten()

for ax, (name, df_report) in zip(axes, dfs.items()):
    ax.axis('off')
    ax.set_title(f"{name} Classification Report")
    table = ax.table(cellText=df_report.round(3).values,
                     colLabels=df_report.columns,
                     cellLoc='center',
                     loc='center')
    table.auto_set_font_size(False)
    table.set_fontsize(12)
    table.auto_set_column_width(col=list(range(len(df_report.columns))))

plt.tight_layout()
plt.show()

# Daha önce eğitilmiş modellerin doğruluk skorlarını tekrar hesapla (model çıktılarından al)
from sklearn.metrics import accuracy_score

# Tekrar hesapla
acc_rf = accuracy_score(y1_test, model1.predict(X1_test_scaled))
acc_gb = accuracy_score(y1_test, model2.predict(scaler2.transform(X1_test)))
acc_svm = accuracy_score(y1_test, model3.predict(scaler3.transform(X1_test)))
acc_ensemble = accuracy_score(y1_test, ensemble_preds)

# Loss değerleri
loss_rf = 1 - acc_rf
loss_gb = 1 - acc_gb
loss_svm = 1 - acc_svm
loss_ens = 1 - acc_ensemble

# Güncellenmiş doğruluk ve kayıp grafikleri
fig, axs = plt.subplots(1, 2, figsize=(12, 5))

# Doğruluk grafiği
axs[0].bar(['RF', 'GB', 'SVM', 'Ensemble'], [acc_rf, acc_gb, acc_svm, acc_ensemble], color=['orange', 'green', 'purple', 'blue'])
axs[0].set_title('Modellerin Doğruluk Oranları')
axs[0].set_ylabel('Accuracy')
axs[0].set_ylim(0.85, 1.0)
axs[0].grid(True, axis='y')

# Kayıp grafiği
axs[1].bar(['RF', 'GB', 'SVM', 'Ensemble'], [loss_rf, loss_gb, loss_svm, loss_ens], color=['orange', 'green', 'purple', 'blue'])
axs[1].set_title('Modellerin Kayıp (Loss) Değerleri')
axs[1].set_ylabel('Loss')
axs[1].set_ylim(0.0, 0.15)
axs[1].grid(True, axis='y')

plt.tight_layout()
plt.show()